apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talos.fullname" . }}-config
  labels:
    {{- include "talos.labels" . | nindent 4 }}
stringData:
  .talos.yaml: {{ .Values.config | toYaml | quote }}

