name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . -f Dockerfile \
           -t docker.pkg.github.com/$GITHUB_REPOSITORY/${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA \
           -t ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest \
           -t docker.pkg.github.com/$GITHUB_REPOSITORY/${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA \
           -t ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest 
    
    - name: Build the Docker image with plugins
      run: docker build . -f Dockerfile.full \
           -t docker.pkg.github.com/$GITHUB_REPOSITORY/${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA \
           -t ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}-full:latest \
           -t docker.pkg.github.com/$GITHUB_REPOSITORY/${{ secrets.DOCKER_IMAGE_NAME }}:$GITHUB_SHA \
           -t ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}-full:latest 
          
    - name: Login to GitHub registrty
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image to registrty
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/${{ secrets.DOCKER_IMAGE_NAME }}
    - name: Push Docker image with plugins to registrty
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/${{ secrets.DOCKER_IMAGE_NAME }}-full
      
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}
    - name: Push Docker image with plugins to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}-full
